use BacterialGrowth;

describe Bacteria;

INSERT IGNORE INTO Bacteria (bacteriaId, bacteriaGenus, bacteriaSpecies, bacteriaStrain) 
VALUES
	(1, 'Bacteroides', 'Bacteroides thetaiotaomicron', 'VPI 5482'),
    (2, 'Bacteroides', 'Bacteroides thetaiotaomicron', 'WAL 2926'),
    (3, 'Bacteroides', 'Bacteroides thetaiotaomicron', 'BTX'),
    (4, 'Bacteroides', 'Bacteroides thetaiotaomicron', 'K3'),
    (5, 'Bacteroides', 'Bacteroides thetaiotaomicron', 'WAL 3304'),
    (6, 'Roseburia', 'Roseburia intestinalis', 'L1-82'),
    (7, 'Roseburia', 'Roseburia intestinalis', 'JCM 17583'),
    (8, 'Roseburia', 'Roseburia intestinalis', 'DSM 14610'),
    (9, 'Roseburia', 'Roseburia intestinalis', 'JCM 31262'),
    (10, 'Roseburia', 'Roseburia intestinalis', 'M50/1'),
    (11, 'Faecalibacterium', 'Faecalibacterium prausnitzii', 'KLE1255'),
    (12, 'Faecalibacterium', 'Faecalibacterium prausnitzii', 'L2-6'),
    (13, 'Faecalibacterium', 'Faecalibacterium prausnitzii', 'M21/2'),
    (14, 'Faecalibacterium', 'Faecalibacterium prausnitzii', 'SL3/3'),
    (15, 'Blautia', 'Blautia hydrogenotrophica', 'DSM 10507'),
    (16, 'Prevotella', 'Prevotella copri', 'CB7'),
    (17, 'Prevotella', 'Prevotella copri', 'CB35'),
    (18, 'Prevotella', 'Prevotella copri', 'DSM 18205'),
    (19, 'Ruminococcus', 'Ruminococcus bromii', 'L2-63'),
    (20, 'Bacteroides', 'Bacteroides fragilis', 'CL05T00C42'),
    (21, 'Bacteroides', 'Bacteroides fragilis', 'CL05T12C13'),
    (22, 'Bacteroides', 'Bacteroides fragilis', 'CL07T00C01'),
    (23, 'Bacteroides', 'Bacteroides fragilis', 'HMW 615'),
    (24, 'Methanobrevibacter', 'Methanobrevibacter smithii', 'ATCC 35061'),
    (25, 'Methanobrevibacter', 'Methanobrevibacter smithii', 'TS146A'),
    (26, 'Methanobrevibacter', 'Methanobrevibacter smithii', 'TS95B'),
    (27, 'Methanobrevibacter', 'Methanobrevibacter smithii', 'TS96C'),
    (28, 'Desulfovibrio', 'Desulfovibrio piger', 'ATCC 29098'),
    (29, 'Desulfovibrio', 'Desulfovibrio piger', 'GOR1'),
    (30, 'Anaerobutyricum', 'Anaerobutyricum hallii', 'DSM 3353'),
    (31, 'Bacteroides', 'Bacteroides thetaiotaomicron', 'DSM 2079'),
    (32, 'Bacteroides', 'Bacteroides uniformis', 'RCC 1835'),
    (33, 'Bifidobacterium', 'Bifidobacterium adolescentis', 'RCC 1139'),
    (34, 'Bilophila', 'Bilophila wadsworthia', 'RCC 662'),
    (35, 'Blautia', 'Blautia hydrogenotrophica', 'DSM 10507'),
    (36, 'Collinsella', 'Collinsella aerofaciens', 'RCC 1366'),
    (37, 'Escherichia', 'Escherichia coli', 'DSM 6050'),
    (38, 'Parabacteroides', 'Parabacteroides merdae', 'RCC 643'),
    (39, 'Faecalibacterium', 'Faecalibacterium prausnitzii', 'DSM 17677'),
    (40, 'Ruminococcus', 'Ruminococcus bromii', 'RCC 1377');