global LOCAL_PROJECT_DIRECTORY
global SERVER_PROJECT_DIRECTORY
global PROJECT_DIRECTORY 
global EXPERIMENT_ANALYSIS_FILE
global MEDIA_ANALYSIS_FILE
global HEADERS_FILE
global EXPERIMENTS_LIST
global MEDIA_LIST


LOCAL_PROJECT_DIRECTORY = '/Users/julia/bacterialGrowth_thesis/'
SERVER_PROJECT_DIRECTORY = '/Users/julia/bacterialGrowth_thesis/'

PROJECT_DIRECTORY = '/Users/julia/bacterialGrowth_thesis/'

# Bash files needed to run the code
EXPERIMENT_ANALYSIS_FILE = 'src/bash_scripts/Lab_files_analysis2.sh'
MEDIA_ANALYSIS_FILE = 'src/bash_scripts/media_file_analysis.sh'

# Files generated by the bash needed in the code
HEADERS_FILE = 'IntermediateFiles/lab_headers.txt'
EXPERIMENTS_LIST = 'IntermediateFiles/listOfFiles.list'
MEDIA_LIST = 'IntermediateFiles/listOfMedia.list'